baseurl = "https://www.kpolley.com"
languageCode = "en"
# title = "Kpolley Blog"
theme = "kiss"
Paginate = 10 # Number of posts per page
enableRobotsTXT = true
googleAnalytics = "G-Q5L67XJHB1"

[params.rss] # Adding this tag enables RSS feed
includeContent = true # Includes whole content in rss
authorName = "Kyle Polley" # Author full name
authorEmail = "kpolley@outlook.com" # Author email

[params.assets]
customCSS = ["css/custom.css"]

[params.info]
homeTitle = "Kpolley Blog" # Title for home page
homeSubtitle = "My outlet for ideas in security; some might actually be good"
adsense = "" # Adsense ID (ID only, without ca-pub-)
enableSocial = false # Adds OpenGraph and Twitter cards
poweredby = false # Adds powered by hugo and kiss below Copyright
related = false # Includes related articles at the bottom of the article
codeCopy = false # Add copy button above code blocks
taxonomiesCount = false # Add taxonomies count

[params.features]
disqusOnDemand = false  # Load Disqus comments on click


[params.opengraph.facebook]
admins = [] # array of Facebook IDs
appID = ""
pageID = ""

[params.opengraph.twitter]
page = "" # Twitter Page username. If not set, params.social.twitter will be used.

[params.social]
twitter = "kplley"
github = "kpolley"
email = "kpolley@outlook.com"
linkedin = "kylepolley"
facebook = ""
instagram = ""
codepen = ""
rss = "index.xml" # Add this to show RSS button in social.

[params.social.config]
platforms = ["twitter","github","linkedin","rss"]

[taxonomies]
tag ="tags"

[blackfriday]
hrefTargetBlank = false
